### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by Locour** [calimero-project/calimero-gui#1]
Hi,

tried to build the 2.3-beta version and got following error:

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.446 s
[INFO] Finished at: 2017-12-22T10:34:43-08:00
[INFO] Final Memory: 20M/119M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project calimero-gui: Compilation failure
[ERROR] /home/user/Desktop/calimero/calimero-gui-2.3-beta/src/tuwien/auto/calimero/gui/PropertyEditorTab.java:[524,49] method does not override or implement a method from a supertype
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Furthermore i got some other different issues compiling calimero with different gradle/maven versions. 
My question is, with which version of gradle (maven) do i have to compile calimero in order to get it work. Please also add this information to the readme/docs.

**Comment by bmalinowsky** [comment]
Yes, there is a glitch in the tags, sorry. 
The correct one (for 2.3-beta) is the one on github. If you require that exact 2.3-beta, you can compile the tools release here (https://github.com/calimero-project/calimero-tools/releases/tag/v2.3-beta).

But actually I forgot to add the stable tag for gui 2.3. In the gui pom, If you replace 2.3-beta in the pom with 2.3 you will pull in the stable ones, which should work without problem.

Wrt gradle: 2.3-beta does not have a gradle setup at all. But for gradle-enabled builds, use the gradle wrapper which uses the appropriate version. The version is specified in _gradle/wrapper/gradle-wrapper.properties_.

Wrt maven: can you be more specific. The only problems I know for myself is compiling on java 9, where some maven plugins have/had problems.

**Comment by Locour** [comment]
Thanks for the fast reply! And many thanks for this great library!

May you add this to the readme so others can see it too.

**Comment by bmalinowsky** [comment]
I put everything into a new release on github (tag v2.3) which should resolve this issue. I also added the gradle wrapper for 2.3 like for other builds. So compilation should work as described in the readme.

**Comment by Locour** [comment]
The new release still throws some errors, i first tried to run it with the following command:
```` bash
mvn clean exec:java -DskipTests -X
````

This gives me the following error:
```` error
[WARNING] 
java.lang.ClassNotFoundException: tuwien.auto.calimero.gui.SwtChecker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:281)
	at java.lang.Thread.run(Thread.java:748)
...
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:java (default-cli) on project calimero-gui: An exception occured while executing the Java class. tuwien.auto.calimero.gui.SwtChecker -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:java (default-cli) on project calimero-gui: An exception occured while executing the Java class. tuwien.auto.calimero.gui.SwtChecker
````

Furthermore when packaging it via
````
mvn clean package -DskipTests
````
and executing the resulting jar it says, that the class SwtChecker could not be found.

<br/>

With which maven/gradle configuration do you compile? I'm using Apache Maven 3.3.9.

**Comment by calimero-project** [comment]
I think you have to force a compile inbetween, otherwise there are no compiled classes after a clean:
`mvn clean compile exec:java -DskipTests -X`

I use mvn -v 3.5.0/3.5.2.
